### PR TITLE
fix for breaking iOS header change in RN 0.40.0

### LINKED ISSUE #541: react-native-camera for iOS doesn't work with latest react-native v0.40.0
### Steps to reproduce
1. Initialize new project using latest react-native v0.40.0
2. npm install react-native-camera
3. react-native link
4. run-ios

### Expected behaviour
Boilerplate app builds and runs

### Actual behaviour
Compilation errors:
`
In file included from [...]/node_modules/react-native-camera/ios/RCTCamera.m:4:
../../react-native/React/Base/RCTLog.h:42:3: error: redefinition of enumerator 'RCTLogLevelInfo'
`

### react-native-camera
**Version**:     "react-native-camera": "^0.4.0",

### PR DESCRIPTION
**Pull request by danieldkim**
For the breaking "iOS native headers moved" [change in RN  0.40.0](https://github.com/facebook/react-native/releases/tag/v0.40.0).  Fixes #541.  Addresses facebook/react-native#11725.

### CODE REVIEW

**Comment by rt2zz** [comment]
🥂

**Comment by danieldkim** [comment]
Thanks! 🥂

**Comment by rt2zz** [comment]
@danieldkim is this change backwards compatible with older react-native versions?

**Comment by danieldkim** [comment]
@rt2zz I haven't tested that yet, tbh.  however, the description of this change the RN release notes suggests not ...

**Comment by danieldkim** [comment]
i'll do a quick test ... hold, please

**Comment by danieldkim** [comment]
@rt2zz it's not.  generates a compiler error in Xcode with 0.39.2.

**Comment by danieldkim** [comment]
Relevant discussion at facebook/react-native#11614.  It looks like the RN team has decided not to support the old import style leaving it to library developers to deal with branching (if they choose).

**Comment by michalmmm** [comment]
Thanks a lot!

**Comment by rt2zz** [comment]
Thanks for looking into that @danieldkim. Looks like v1 is coming up :D

**Comment by merapi** [comment]
guys, you integrated breaking change into master without changing version... (my project stopped working)

**Comment by danieldkim** [comment]
@rt2zz OK, I've been pointing my `package.json` at `master` to get the latest and greatest.  `master` should now only get critical bug fixes and I should track the `next` branch for shiny new stuff?

**Comment by danieldkim** [comment]
I mean I have no choice since I am on RN 0.40.0, so if that isn't the case my only option to make sure I always get the latest shiny new is to regularly sync to my fork, which would seem kinda backward.

**Comment by rt2zz** [comment]
@danieldkim ya this is non-ideal *but* most of the ecosystem is not rn 0.40 ready yet (maps, branch off the top of my head), so I think we are going to see more users point to master on <0.40 than vice-versa. Going to be pain either way.

In the short term I am going to merge all new features against #next branch, so I think if you want to more or less continue how things were I would point you installation to `lwansbrough/react-native-camera#next`. Hopefully this will be short lived.

**Comment by danieldkim** [comment]
@rt2zz great, thanks that'll make things easier for me.  fyi, maps [has pushed their fix for this out](https://github.com/airbnb/react-native-maps/pull/923#issuecomment-270829807).

**Comment by ksrawat** [comment]
@danieldkim is it possible to draw a rectangle/bound line when barcode is detected? I know we get bound data, could you please simplify this for me if possible. would appreciate this.
