### ISSUE TITLE
react-native-camera for iOS doesn't work with latest react-native v0.40.0

### ISSUE THREAD

**Issue by michalmmm** [lwansbrough/react-native-camera#541]
### Steps to reproduce
1. Initialize new project using latest react-native v0.40.0
2. npm install react-native-camera
3. react-native link
4. run-ios

### Expected behaviour
Boilerplate app builds and runs

### Actual behaviour
Compilation errors:
`
In file included from [...]/node_modules/react-native-camera/ios/RCTCamera.m:4:
../../react-native/React/Base/RCTLog.h:42:3: error: redefinition of enumerator 'RCTLogLevelInfo'
`

### react-native-camera
**Version**:     "react-native-camera": "^0.4.0",

**Comment by chirag04** [comment]
refer the change for RN 0.40. Feel free to send a PR for new HEADER_SEARCH_PATH and fixing the imports.
